Add config options for new completions modes (ver 2)
julia-vscode/julia-vscode pull request #1963
Opened 2021-02-19 09:44 UTC by ZacLN

Fixes #.

For every PR, please check the following:
- [x] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.
- [x] Changelog mention. If this PR should be mentioned in the CHANGELOG, please edit the CHANGELOG.md file in this PR.

2021-02-19 09:46 UTC, pfitzseb approved these changes

2021-03-12 21:31 UTC, davidanthoff commented
Needs a merge conflict resolution.

2021-03-12 21:33 UTC, davidanthoff requested changes
Needs a merge conflict resolution.

2021-05-12 15:55 UTC, davidanthoff approved these changes

2021-05-19 16:35 UTC, merged