Add Send current line of selection to REPL to context menu
julia-vscode/julia-vscode pull request #2667
Opened 2022-01-05 02:09 UTC by JaapHaitsma

Fixes #2656

2022-01-05 09:01 UTC, pfitzseb requested changes

2022-01-05 09:01 UTC, pfitzseb commented on package.json
> +                    "group": "z_commands"
I think I'd prefer
```suggestion
                    "command": "language-julia.executeCodeBlockOrSelection",
                    "when": "editorLangId == julia || editorLangId == juliamarkdown",
                    "group": "z_commands"
```
`executeJuliaCodeInREPL` is mostly unused at this point.

2022-01-05 12:16 UTC, pfitzseb approved these changes

2022-01-13 11:49 UTC, JaapHaitsma commented
Anything else that needs to be done before this can be merged into master?

2022-02-15 10:48 UTC, merged