remove time wasting dialog
julia-vscode/julia-vscode pull request #2720
Opened 2022-02-07 03:12 UTC by xgdgsc

remove time wasting dialog

2022-02-07 10:08 UTC, pfitzseb commented
Not a fan of this. Killing a tmux session that you may not even have open in VS Code and which may or may not contain an arbitrary number of other running processes seems like a recipe for disaster.

2022-02-07 10:15 UTC, xgdgsc commented
Maybe you should poll somewhere to find how people use this. For me the only process I would want in this tmux session is julia. I can' t imagine anyone would want to run other process inside the same session in the tiny horizontal terminal inside vscode rather than starting a terminal app and another tmux session elsewhere. I think the only difference between a persistent and non-persistent is the "persistent", other command behavior should be identical. Or you could make this only appear at first time to inform users and never appear again.

2022-02-07 10:41 UTC, pfitzseb commented
That's fair. Maybe just add an additional `Yes, always` choice?

2022-02-08 04:49 UTC, xgdgsc commented
Thanks. added https://github.com/julia-vscode/julia-vscode/issues/1533 also in this PR.

2022-02-14 16:07 UTC, pfitzseb requested changes
Left a few comments inline, but this looks good overall.

2022-02-14 16:07 UTC, pfitzseb commented on package.json
> +                },
```suggestion
                "julia.persistentSession.warnOnKill": {
                    "type": "boolean",
                    "default": true,
                    "scope": "machine-overridable",
                    "description": "Warn when stopping a persistent session."
                },
```

2022-02-14 16:07 UTC, pfitzseb commented on src/interactive/repl.ts
> +async function checkKillPersistentSession() {
```suggestion
async function confirmKill() {
```

2022-02-14 16:07 UTC, pfitzseb commented on src/interactive/repl.ts
> +    if (persistentStopWarning || vscode.workspace.getConfiguration('julia').get<boolean>('persistentSession.stopWarning') === false) {
Would be good to share the result of `vscode.workspace.getConfiguration('julia')` with the code below.

2022-02-14 16:07 UTC, pfitzseb commented on src/interactive/repl.ts
> +async function stopREPL() {
This should just be `killREPL` below, no? I don't see the need for an additional method.

2022-02-14 16:07 UTC, pfitzseb commented on src/interactive/repl.ts
> +async function stopREPLInPersistent() {
I think this can live in `killREPL` directly. If not, let's call it `maybeKillPersistentSession`; that name seems a bit clearer.

2022-02-15 02:54 UTC, xgdgsc commented on src/interactive/repl.ts
> +let persistentStopWarning: boolean = false
https://github.com/julia-vscode/julia-vscode/pull/2720/commits/0b1afa7ba078c19ac0979d5be7f787ffd5d7c5ab

2022-02-15 10:37 UTC, pfitzseb approved these changes
Looking good! Thanks for bearing with me :)

2022-02-15 10:50 UTC, merged